backend:
  name: github
  repo: olimpiadi-informatica/website
  auth_scope: repo
  open_authoring: true
  site_domain: abbc5244-c379-41d2-8c38-bc6f6f87afaa
  branch: main
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
site_url: 'https://www.olimpiadi-informatica.it/'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/'
    create: true
    format: 'toml-frontmatter'
    slug: '{{slug}}'
    preview_path: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Keywords', name: 'description', widget: 'string', required: false }
      - label: "Taxonomies"
        name: "taxonomies"
        widget: "object"
        collapsed: false
        fields:
          - label: "Gare"
            name: "gare"
            widget: "select"
            multiple: true 
            required: false
            max: 1
            options: ["scolastiche", "territoriali", "nazionali", "stage", "internazionali", "digit"]
          - label: "Edizioni"
            name: "edizioni"
            widget: "select"
            multiple: true 
            required: false
            max: 1
            options: [
              "2028-2029", "2027-2028", "2026-2027", "2025-2026", "2024-2025", "2023-2024", "2022-2023",
              "2021-2022", "2020-2021", "2019-2020", "2018-2019", "2017-2018", "2016-2017", "2015-2016",
              "2014-2015", "2013-2014", "2012-2013", "2011-2012", "2010-2011", "2009-2010", "2008-2009",
              "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999",
            ]
      - label: 'More...'
        name: 'extra'
        widget: 'object'
        collapsed: true
        fields:
          - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: false }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
          - { label: 'Highlighted', name: 'highlighted', widget: 'boolean', required: false }
          - { label: 'Override Updated Date', name: 'override_updated', widget: 'datetime', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pagine'
    label: 'Pagine statiche'
    folder: 'content/pagine/'
    format: 'toml-frontmatter'
    slug: '{{slug}}'
    preview_path: 'pagine/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
